// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://ncngbdjnyshpefhftamp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jbmdiZGpueXNocGVmaGZ0YW1wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNDY4OTYsImV4cCI6MjA2NTgyMjg5Nn0.jAm8hUzAtHwLylSFm-5QX6i2wTQAQV6aA-dhp1u9qOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
