// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggayrvnojoujmhochepf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnYXlydm5vam91am1ob2NoZXBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTY3OTAsImV4cCI6MjA2NTMzMjc5MH0.EbGVd5iQjtOrNuzs5n4BohShdpgJWnKp8yjBb1W54WY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);